# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


development:
  secret_key_base: 60e5483ffefd8b18fb44f4fb8a285d007a1e79a583bbe9bfd1f18722ce204d2a179334b8cd31e629a6c3297906caa6d0ae89db82ce3bfe807d664d8e5f1a6c7d

test:
  secret_key_base: 80a0dd05520dd37c2da8fb8df9ad431a2a518ee21c1c6e8e64244e37d47640ef4a01a389722aecf23c0c1d4221717c1d07a868adbfd930bd598eefebefe9d403
  requests:
    real: false
    course: '100'
    discussion_topic_id: "239829"
    base_url: "http://localhost:3100/"
    api_keys:
      teacher: "Not a  valid API key"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  requests:
    real: false
